# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&6Czechcraft Query &8>> '
debug-enabled: true

# Refresh rates in seconds.
refresh-rates:
  server_info: 300
  next_vote: 300