# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&6Czechcraft Query &8| '
debug-enabled: false

# Default server slug to use
server-slug: 'pvpcraft'

# Force all cached responses to update when a vote from Czech-craft.eu is received.
force-update-on-vote: true

# Listen to when the server advances in the leaderboard and broadcast a message.
advance:
  enabled: true
  rewards:
    broadcast:
      - ' '
      - '&7Server advanced to position &8#&6%serverPosition% &7on &6Czech&8-&6craft&8.&6eu &7with &e%serverVotes% &7votes!'
      - ' '

# Listen to when the server drops in the leaderboard and broadcast a message.
drop:
  enabled: true
  rewards:
    broadcast:
      - ' '
      - '&7Server dropped to position &8#&6%serverPosition% &7on &6Czech&8-&6craft&8.&6eu &7with &e%serverVotes% &7votes!'
      - ' '

# When the player can vote again.
user-can-vote:
  enabled: true
  rewards:
    inform:
      - '&7You can vote again!'

# Refresh rates in seconds.
refresh-rates:
  server_info: 300
  next_vote: 300
  server_votes: 300
  user_votes: 300
  top_votes: 300
  server_votes_monthly: 300

# Time formats
formats:
  duration: "HH:mm:ss"