# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&6Czechcraft Query &8| '
debug-enabled: false

# Default server slug to use
server-slug: 'pvpcraft'

# Force all cached responses to update when a vote from Czech-craft.eu is received.
force-update-on-vote: true

# Refresh rates in seconds.
refresh-rates:
  server_info: 300
  next_vote: 300

# Time formats
formats:
  duration: "HH:mm:ss"