name: ${project.name}
version: ${project.version}
main: ${project.groupId}.QueryPlugin
authors: [ qwz ]
softdepend: [ PlaceholderAPI, Votifier ]
commands:
  czechcraftquery:
    description: Main plugin command.
    aliases: [ ccq, cq, czechquery, query ]