name: ${project.name}
version: ${project.version}
main: ${project.groupId}.QueryPlugin
authors: [ Wertik1206 ]
softdepend: [PlaceholderAPI]
commands:
  czechcraftquery:
    description: Main plugin command.
    aliases: [ ccq, cq, czechquery, query ]